# Generated by Django 4.2.7 on 2024-10-14 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('verse_text', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reflection', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
